#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

components-$(CONFIG_APP_HYDRA_APP) += hydra-app
hydra-app: common libsel4 libmuslc libsel4muslcsys libsel4simple-default libsel4simple libsel4vka libsel4allocman libsel4vspace \
	libsel4platsupport libsel4utils libcpio libelf libsel4simple-default libattest
