#
# Copyright 2015, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

components-$(CONFIG_FUEL_LEVEL_APP) += fuel-level-app
fuel-level-app: common libsel4 libmuslc libsel4muslcsys
